<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="Online_Job_Portal.Admin.Dashboard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Admin Dashboard</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pretium, velit eget tincidunt vulputate, nisi lectus volutpat elit, sit amet interdum purus ipsum eu metus. Quisque sodales gravida condimentum. Fusce ut sem ante. Mauris vitae diam magna. Proin ac ultricies dolor. Sed luctus non ex maximus accumsan. Ut urna orci, ullamcorper sed arcu at, fringilla bibendum nisi. Praesent nec sodales dui. Vivamus vitae viverra magna. Sed quis consectetur turpis. Sed laoreet felis nisl, vel tristique ante imperdiet vitae.

Quisque aliquam magna sed diam blandit, a ultricies nisi pellentesque. Integer ut tortor lectus. Praesent et augue eu justo aliquet egestas. Phasellus iaculis massa quis ex pretium tristique. Nulla euismod scelerisque euismod. Nullam libero sem, placerat ac leo id, hendrerit posuere nulla. Mauris blandit, neque sit amet varius tincidunt, est augue gravida massa, vitae pretium ipsum magna et elit. Curabitur lectus nibh, ullamcorper vitae justo et, viverra mattis mauris. Suspendisse ornare mi placerat, suscipit justo a, volutpat nulla.

Sed a nisi sollicitudin, finibus turpis in, dapibus ex. Donec turpis magna, aliquam a libero et, porta cursus justo. Phasellus eget velit a risus maximus auctor at vitae leo. Sed in hendrerit erat. Aliquam lacinia ultrices ante sit amet lobortis. Ut placerat blandit enim sit amet commodo. Aliquam sagittis lorem convallis nisi imperdiet, sit amet lobortis leo sodales. Etiam pharetra velit suscipit pellentesque iaculis. Fusce facilisis congue tincidunt. Quisque nibh enim, scelerisque et sapien non, lacinia aliquet justo. Donec lobortis nulla dolor, eu facilisis quam pretium non. Vestibulum id lectus dui. Praesent a justo interdum, gravida metus sit amet, sollicitudin lorem. Quisque lacinia ligula eu magna hendrerit imperdiet.

Nulla facilisi. Nunc lobortis nulla vitae elit vestibulum, sed elementum metus faucibus. Phasellus placerat mauris at turpis sodales hendrerit. Nunc porttitor vitae diam non luctus. Nam suscipit ligula suscipit ante sollicitudin suscipit. Morbi aliquam ut mi eu maximus. Integer tincidunt nibh ac gravida mattis. Pellentesque at pellentesque metus.

Phasellus tellus massa, hendrerit id ex ut, scelerisque cursus erat. Vivamus vehicula ac lectus vel iaculis. Sed fermentum, dolor cursus aliquet ultricies, risus eros condimentum ante, sed consectetur tortor ex ac metus. Nullam tempor gravida diam. Aliquam cursus arcu ac urna faucibus feugiat. Aliquam magna neque, venenatis eget ultricies sit amet, convallis id eros. Maecenas ut lacus id nibh euismod sodales et id ex. Suspendisse potenti. Morbi et sapien ligula. Aenean gravida, ligula a pretium dapibus, dui risus mollis massa, at viverra eros ipsum sit amet urna. Fusce rhoncus commodo odio. Mauris neque libero, consequat quis pellentesque at, gravida id nulla. Duis feugiat arcu et pellentesque vehicula.</p>
</asp:Content>
